- name: manager node- Install docker, create swarm, install jenkins
  hosts: swarm-manager
  connection: local
  become: true
  roles:
    - docker-installation
    - docker-swarm-init
    - jenkins
  
- name: Add worker to swarm
  hosts: swarm-worker
  become: true
  roles:
    - docker-installation
    - docker-swarm-add-worker
