- name: Install docker
  hosts: servers
  become: true
  roles:
    - docker-installation

- name: Create docker swarm
  hosts: swarm-manager
  become: true
  roles:
    - docker-swarm-init
  
- name: Add worker to swarm
  hosts: swarm-worker
  become: true
  roles:
    - docker-swarm-add-worker