- name: Change jenkins JAVA options
  lineinfile:
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: start jenkins service and enable on boot
  service: 
    name: jenkins 
    state: started
    enabled: yes